# Generated by Django 4.0 on 2022-02-08 06:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.token'),
            preserve_default=False,
        ),
    ]
