# Generated by Django 4.0 on 2022-02-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
