# Generated by Django 4.0.2 on 2022-02-24 16:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
